#### Config for CB-Spider PoC ####

## Config for OpenStack ##
openstack:

  # OpenStack Credential Info
  domain_name: {domain_name}
  # identity_endpoint: http://{ip}/identity/v3   # for devstak-queens
  identity_endpoint: http://{ip}:5000/v3
  password: {password}
  project_id: {project_id}
  username: {username}
  region: {region}

  # OpenStack VM Deployment Info
  vm_name: {vm_name}
  image_id: {image_id}
  flavor_id: {flavor_id}
  network_id: {network_id}
  security_groups: {security_groups}
  keypair_name: {keypair_name}

  # OpenStack Test VM Info
  server_id: {server_id}

  image_info:
    name: mcb_custom_image.iso

  keypair_info:
    name: mcb-test-key

  security_group_info:
    name: mcb-test-security

  vnet_info:
    name: mcb-test-vnet

  subnet_info:
      id: {subnet_id}

  router_info:
    name: mcb-router
    gateway_id: {gateway_id}
    adminstatup: true

## Config for AZURE ##
azure:

  # Azure Credential Info
  client_id: {client_id}
  client_secret: {client_secret}
  tenant_id: {tenant_id}
  subscription_id: {subscription_id}

  # Azure VM Deployment Info
  location: {location}
  vm_size: {vm_size}
  image:
    publisher: {publisher}
    offer: {offer}
    sku: {sku}
    version: {version}
  os:
    compute_name: {compute_name}
    admin_username: {admin_username}
    admin_password: {admin_password}
  nic:
    id: {id}

  # Azure Test VM Info
  group_name: {group_name}
  vm_name: {vm_name}

  image_info:
    group_name: {group_name}
    name: {name}

  public_ip:
    group_name: {group_name}
    name: {name}

  security_group:
    group_name: {group_name}
    name: {name}

  virtual_network:
    group_name: {group_name}
    name: {name}

  network_interface:
    group_name: {group_name}
    name: {name}


## Config for Cloudit ##
cloudit:

  # Cloudit Credential Info
  identity_endpoint: {identity_endpoint}
  auth_token: {token}
  tenant_id: tnt0009
  #  auth_token: ddd8e54a5bac82eea3de7c347ff8a253d0dc563d
  #  tenant_id: tnt0008
  server_id: 7b35148e-b033-4749-a29e-12beddaebbfa
  
  # Cloudit VM Create Info
  vm_info:
    template_id: 2813a6ed-66f8-4041-9cfa-2cb5cb416520
    spec_id: 1c38e438-ede9-4df5-8775-2ce791698924
    name: mcb-vm
    root_password: 1qa2ws3ed!A
    subnet_addr: 10.0.8.0
    sec_groups: b2be62e7-fd29-43ff-b008-08ae736e092a
    description: mcb-test-vm
    protection: 0

  # Cloudit Resource Create Info
  resource:
    image:
      name: mcb-test-img
    public_ip:
      name: mcb-test-pubip
    security_group:
      name: mcb-test-sg
    vnet_info:
      name: mcb-test-vnet
    vnic_info:
      vm_id: 025e5edc-54ad-4b98-9292-6eeca4c36a6d
      mac: AC:DE:48:00:08:05
    vm_info:
      name: mcb-test-vm
